### ISSUE TITLE
Call to a member function dirlist() on bool - in custom fonts when using wp-cli.phar

### ISSUE THREAD

**Issue by PhilETaylor** [reduxframework/redux-extensions#397]
When running the wp-cli command line tool https://wp-cli.org from @schlessera , the following Fatal Error occurs 

(v4.3.21 works fine, v4.3.24 breaks for sure) 

```
php wp-cli.phar --allow-root cache flush
```

```
Fatal error: Uncaught Error: Call to a member function dirlist() on bool in /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/extensions/custom_fonts/class-redux-extension-custom-fonts.php:239
Stack trace:
#0 /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/extensions/custom_fonts/class-redux-extension-custom-fonts.php(103): Redux_Extension_Custom_Fonts->get_fonts()
#1 /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(250): Redux_Extension_Custom_Fonts->__construct()
#2 /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(1611): Redux::load_extensions()
#3 /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-extensions.php(118): Redux::set_extensions()
#4 /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-extensions.php(28): Redux_Extensions->load()
#5 /var/www/html/wp-content/plugins/redux-framework/redux-core/framework.php(500): Redux_Extensions->__construct()
#6 /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(398): ReduxFramework->__construct()
#7 /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/classes/class-redux-api.php(428): Redux::load_redux()
#8 /var/www/html/wp-includes/class-wp-hook.php(308): Redux::create_redux()
#9 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#10 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#11 /var/www/html/wp-settings.php(595): do_action()
#12 phar:///var/www/html/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('...')
#13 phar:///var/www/html/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#14 phar:///var/www/html/wp-cli.phar/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#15 phar:///var/www/html/wp-cli.phar/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process()
#16 phar:///var/www/html/wp-cli.phar/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#17 phar:///var/www/html/wp-cli.phar/php/boot-phar.php(11): include('...')
#18 /var/www/html/wp-cli.phar(4): include('...')
#19 {main}
  thrown in /var/www/html/wp-content/plugins/redux-framework/redux-core/inc/extensions/custom_fonts/class-redux-extension-custom-fonts.php on line 239
OA
```

Others are also having this issue, I found this site in google search which is down with this same root error - https://www.waermewende-nordwest.de (not our site)

**Comment by kprovance** [comment]
Please update to version 4.3.25.
